import React, { useState, useEffect, useCallback, useRef } from 'react';
import { Chat } from '@google/genai';
import { User } from 'firebase/auth';
import { Message, Conversation, FileMessage } from './types';
import { createChat, generateTitle } from './services/geminiService';
import { fileStorage } from './services/fileStorage';
import { onAuthStateChange } from './services/authService';
import { personalityService } from './services/personalityService';
import { personalityTemplates } from './data/personalityTemplates';
import { voiceService } from './services/voiceService';
import { searchService } from './services/searchService';
import { templateService, MessageTemplate } from './services/templateService';
import ChatPanel from './components/ChatPanel';
import SidePanel from './components/SidePanel';
import PanelToggleButton from './components/PanelToggleButton';
import useMediaQuery from './hooks/useMediaQuery';
import EarthIcon from './components/icons/EarthIcon';
import AuthPage from './components/AuthPage';
import UserProfile from './components/UserProfile';
import PWAInstallPrompt from './components/PWAInstallPrompt';
import PWAUpdateNotification from './components/PWAUpdateNotification';
import InstallButton from './components/InstallButton';
import PWAStatusToggle from './components/PWAStatusToggle';
import QuickStartGuide from './components/QuickStartGuide';
import VoiceSettings from './components/VoiceSettings';
import SearchPanel from './components/SearchPanel';
import TemplatePanel from './components/TemplatePanel';
import PersonalityManager from './components/PersonalityManager';
import ConversationAnalytics from './components/ConversationAnalytics';
import ExportImportPanel from './components/ExportImportPanel';
import CommandPalette from './components/CommandPalette';
import KeyboardShortcutsHelp from './components/KeyboardShortcutsHelp';
import FeatureToolbar from './components/FeatureToolbar';
import QuickAccessButton from './components/QuickAccessButton';
import FeatureDiscovery from './components/FeatureDiscovery';
import FeatureNotification from './components/FeatureNotification';
import ErrorBoundary from './components/ErrorBoundary';
import LoadingSpinner from './components/LoadingSpinner';
import { keyboardShortcutService } from './services/keyboardShortcutService';
import { exportImportService } from './services/exportImportService';
import { analytics, trackFeatureUsage, trackError } from './utils/analytics';
import { performanceMonitor } from './utils/performance';